### ISSUE TITLE
Search: Results Page

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dapp#313]
Once the designs are final(-ish), a search results page should be built.

See https://app.zeplin.io/project/59fa2311bac7acbc8d953da9?seid=5b51788f2ad605b11e38f756

**Comment by franckc** [comment]
This includes:
- search bar
   - search box
   - listing type picker on left side of search box
   - price filter
   - availability filter for fractional usage listings
   - links with pre-defined filters/sorting on the right of the search box
  - sort by button (price low to high, most to least recent creation date, ...)
- displaying search results based on actions from search bar

Note: the "location picker" component is not included in this task since it is a bit more complex. It will be tracked as separate issue #366

**Comment by micahalcorn** [comment]
Resolved by https://github.com/OriginProtocol/origin-dapp/pull/396 ✅
