### ISSUE TITLE
Listing Creation: Location Field

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin-dapp#613]
[micah] **Edit** 9/27/2018

The location field should not appear in step 2️⃣ of the listing creation form.

-------------
The "Location" field on new listings is not being saved to IPFS. Are we getting rid of this field?

**Comment by franckc** [comment]
Correct - we decided location will be handled after V1 because we could not agree on a proper schema for handling location... Also we did not have enough time to implement google maps API integration for address auto-complete and standardization...

Now I think we might still be showing the text input box for Location when creating some listing types in the DApp ? We should remove it because that data just get black holed and not saved in IPFS...

**Comment by micahalcorn** [comment]
Editing this title and opening comment 🛠
